### ISSUE TITLE
(off-topic) Need help with a game translation

### ISSUE THREAD

**Issue by Hexaae** [LaZar00/Aeris#2]
Hi,
sorry if I try to get in touch with you through GitHub but I couldn't contact you through DLan or GOG (I sent a friend request long ago).

I'm Hexaae, and we're trying to complete Italian translation for good old "Star Trek 25th Anniversary Enhanced CD" but we need some little help with extracted bitmap fonts (.fnt) and images (.bmp) to adapt them to the Italian language... 😔
Please, let's get in touch... you can find me on GOG or Steam (friend code: 32559187 )

**Comment by LaZar00** [comment]
Comment not of this tool.
